/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tech.charliewilkins.best;

import org.junit.jupiter.api.Test;

// import tech.charliewilkins.best.App;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
